import type { Metadata } from 'next';
import { Navigation } from '../../_components/Navigation';
import { roboto, roboto_condensed } from './ui/fonts';
import './globals.scss';
import styles from './rwd.module.scss';
import { Suspense } from 'react';
import { NavigationSkeleton } from '../../_components/Navigation/Skeleton';

const { wrapper } = styles;

export const metadata: Metadata = {
  title: 'JS Gladiators Academy',
  description: 'Generated by create next app',
};

const allUsedFonts = [roboto.variable, roboto_condensed.variable];
const computedFonts = allUsedFonts.join(' ');

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={computedFonts}>
      <body>
        <Suspense fallback={<NavigationSkeleton />}>
          <Navigation />
        </Suspense>
        <main className={wrapper}>{children}</main>
      </body>
    </html>
  );
}
